// apps/my-react-app/src/app/app.tsx
import { myLib } from '@nx-monorepo/my-lib';
import React from 'react';

import './app.css';

import { ReactComponent as Logo } from './logo.svg';

export function App() {
  /*
   * Replace the elements below with your own.
   *
   * Note: The corresponding styles are in the ./app.css file.
   */
  return (
    <div className="app">
      <header className="flex">
        <Logo width="75" height="75" />
        <h1>Welcome to my-react-app!</h1>
      </header>
      <h2>This app is using {myLib()}</h2>
    </div>
  );
}

export default App;

// apps/my-ng-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { myLib } from '@nx-monorepo/my-lib';

@Component({
  selector: 'nx-monorepo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'my-ng-app';
  mySubtitle = myLib();
}

<header class="flex">
  <img
    alt="Nx logo"
    width="75"
    src="https://nx.dev/assets/images/nx-logo-white.svg"
  />
  <h1>Welcome to {{ title }}!</h1>
</header>
<h2>This app is using {{mySubtitle}}!</h2>
